openapi: 3.0.3
info:
  title: Choreo Sample - Book List - Nodejs REST API Service
  description: >-
    This is a sample API specification for a simple reading list application with in-memory cache
    written in Nodejs
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Choreo
  url: https://choreo.dev
servers:
  - url: http://localhost:8080
tags:
  - name: books
    description: In-memory book list cache API
paths:
  /api/businesses:
    post:
      summary: Create a new business entry
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Business'
      responses:
        '201':
          description: Business created successfully
        '400':
          description: Invalid input
components:
  schemas:
    Business:
      type: object
      properties:
        name:
          type: string
        business_name:
          type: string
        email:
          type: string
        website:
          type: string
      required:
        - name
        - business_name
        - email
        - website